import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";

const clashDisplay = localFont({
  src: [
    {
      path: '../public/fonts/BebasNeue-Regular.woff2',
      weight: '400',
      style: 'regular',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clashDisplay.className}>{children}</body>
    </html>
  );
}
